//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazeez.Entities.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LazeezEntities : DbContext
    {
        public LazeezEntities()
            : base("name=LazeezEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<lkp_City> lkp_City { get; set; }
        public virtual DbSet<lkp_Country> lkp_Country { get; set; }
        public virtual DbSet<lkp_District> lkp_District { get; set; }
        public virtual DbSet<lkp_FoodType> lkp_FoodType { get; set; }
        public virtual DbSet<lkp_MealException> lkp_MealException { get; set; }
        public virtual DbSet<lkp_SourceImage> lkp_SourceImage { get; set; }
        public virtual DbSet<lkp_SourceType> lkp_SourceType { get; set; }
        public virtual DbSet<lkp_UserType> lkp_UserType { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Restaurant> tbl_Restaurant { get; set; }
        public virtual DbSet<tbl_RestaurantBranch> tbl_RestaurantBranch { get; set; }
        public virtual DbSet<tbl_RestaurantFood> tbl_RestaurantFood { get; set; }
        public virtual DbSet<tbl_RestaurantMeal> tbl_RestaurantMeal { get; set; }
        public virtual DbSet<tbl_RestaurantMealException> tbl_RestaurantMealException { get; set; }
        public virtual DbSet<tbl_RestaurantMenu> tbl_RestaurantMenu { get; set; }
        public virtual DbSet<tbl_RestaurantOrder> tbl_RestaurantOrder { get; set; }
        public virtual DbSet<tbl_RestaurantOrderMeal> tbl_RestaurantOrderMeal { get; set; }
        public virtual DbSet<tbl_RestaurantPromotion> tbl_RestaurantPromotion { get; set; }
        public virtual DbSet<tbl_RestaurantPromotionMeal> tbl_RestaurantPromotionMeal { get; set; }
        public virtual DbSet<tbl_RestaurantTable> tbl_RestaurantTable { get; set; }
        public virtual DbSet<tbl_RestaurantTime> tbl_RestaurantTime { get; set; }
        public virtual DbSet<tbl_RestaurantUserReview> tbl_RestaurantUserReview { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<tbl_UserDeviceToken> tbl_UserDeviceToken { get; set; }
        public virtual DbSet<tbl_UserException> tbl_UserException { get; set; }
        public virtual DbSet<tbl_UserInterest> tbl_UserInterest { get; set; }
        public virtual DbSet<tbl_UserOrder> tbl_UserOrder { get; set; }
        public virtual DbSet<tbl_UserRestaurant> tbl_UserRestaurant { get; set; }
         
    }
}
