//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazeez.Entities.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RestaurantOrderMeal
    {
        public int ID { get; set; }
        public int RestaurantOrderID { get; set; }
        public int RestaurantMealID { get; set; }
        public Nullable<int> RestaurantPromotionMealID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int CreatorUserID { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public int ModifiedUserID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual tbl_RestaurantMeal tbl_RestaurantMeal { get; set; }
        public virtual tbl_RestaurantOrder tbl_RestaurantOrder { get; set; }
        public virtual tbl_RestaurantPromotionMeal tbl_RestaurantPromotionMeal { get; set; }
    }
}
