//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazeez.Entities.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_User()
        {
            this.tbl_RestaurantUserReview = new HashSet<tbl_RestaurantUserReview>();
            this.tbl_UserDeviceToken = new HashSet<tbl_UserDeviceToken>();
            this.tbl_UserException = new HashSet<tbl_UserException>();
            this.tbl_UserInterest = new HashSet<tbl_UserInterest>();
            this.tbl_UserOrder = new HashSet<tbl_UserOrder>();
            this.tbl_UserRestaurant = new HashSet<tbl_UserRestaurant>();
        }
    
        public int ID { get; set; }
        public int UserTypeID { get; set; }
        public Nullable<int> RestaurantBranchID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string FacebookAccount { get; set; }
        public string InstgramAccount { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int NumberOfRestaurant { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int CreatorUserID { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public int ModifiedUserID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual lkp_UserType lkp_UserType { get; set; }
        public virtual tbl_RestaurantBranch tbl_RestaurantBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RestaurantUserReview> tbl_RestaurantUserReview { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UserDeviceToken> tbl_UserDeviceToken { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UserException> tbl_UserException { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UserInterest> tbl_UserInterest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UserOrder> tbl_UserOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UserRestaurant> tbl_UserRestaurant { get; set; }
    }
}
