//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazeez.Entities.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Restaurant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Restaurant()
        {
            this.tbl_RestaurantBranch = new HashSet<tbl_RestaurantBranch>();
            this.tbl_RestaurantFood = new HashSet<tbl_RestaurantFood>();
            this.tbl_RestaurantMeal = new HashSet<tbl_RestaurantMeal>();
            this.tbl_RestaurantMenu = new HashSet<tbl_RestaurantMenu>();
            this.tbl_RestaurantOrder = new HashSet<tbl_RestaurantOrder>();
            this.tbl_RestaurantPromotion = new HashSet<tbl_RestaurantPromotion>();
            this.tbl_RestaurantTable = new HashSet<tbl_RestaurantTable>();
            this.tbl_RestaurantTime = new HashSet<tbl_RestaurantTime>();
            this.tbl_RestaurantUserReview = new HashSet<tbl_RestaurantUserReview>();
            this.tbl_UserRestaurant = new HashSet<tbl_UserRestaurant>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string HotLine { get; set; }
        public int Type { get; set; }
        public int NumberOfTables { get; set; }
        public int NumberOfStaff { get; set; }
        public bool CanReserveTables { get; set; }
        public bool AllowSmoking { get; set; }
        public string TimeToDelivery { get; set; }
        public decimal Tax { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int CreatorUserID { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public int ModifiedUserID { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RestaurantBranch> tbl_RestaurantBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RestaurantFood> tbl_RestaurantFood { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RestaurantMeal> tbl_RestaurantMeal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RestaurantMenu> tbl_RestaurantMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RestaurantOrder> tbl_RestaurantOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RestaurantPromotion> tbl_RestaurantPromotion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RestaurantTable> tbl_RestaurantTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RestaurantTime> tbl_RestaurantTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RestaurantUserReview> tbl_RestaurantUserReview { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UserRestaurant> tbl_UserRestaurant { get; set; }
    }
}
